// <auto-generated />
using MAM_Sales_Tax.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MAM_Sales_Tax.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240123220242_ChangeDoublesToDecimalType")]
    partial class ChangeDoublesToDecimalType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MAM_Sales_Tax.Models.ImportTaxCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ImportTaxCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Uncategorised0",
                            Rate = 0m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Uncategorised5",
                            Rate = 5m
                        });
                });

            modelBuilder.Entity("MAM_Sales_Tax.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ImportTaxCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TaxCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImportTaxCategoryId");

                    b.HasIndex("TaxCategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImportTaxCategoryId = 1,
                            Name = "Book",
                            Price = 12.49m,
                            TaxCategoryId = 3
                        },
                        new
                        {
                            Id = 2,
                            ImportTaxCategoryId = 1,
                            Name = "Music CD",
                            Price = 14.99m,
                            TaxCategoryId = 2
                        },
                        new
                        {
                            Id = 3,
                            ImportTaxCategoryId = 1,
                            Name = "Chocolate Bar",
                            Price = 0.85m,
                            TaxCategoryId = 4
                        },
                        new
                        {
                            Id = 4,
                            ImportTaxCategoryId = 2,
                            Name = "Imported Box of Chocolates",
                            Price = 10.00m,
                            TaxCategoryId = 4
                        },
                        new
                        {
                            Id = 5,
                            ImportTaxCategoryId = 2,
                            Name = "Imported Bottle of Perfume",
                            Price = 47.50m,
                            TaxCategoryId = 2
                        },
                        new
                        {
                            Id = 6,
                            ImportTaxCategoryId = 2,
                            Name = "Imported Bottle of Perfume",
                            Price = 27.99m,
                            TaxCategoryId = 2
                        },
                        new
                        {
                            Id = 7,
                            ImportTaxCategoryId = 1,
                            Name = "Bottle of Perfume",
                            Price = 18.99m,
                            TaxCategoryId = 2
                        },
                        new
                        {
                            Id = 8,
                            ImportTaxCategoryId = 1,
                            Name = "Packet of Paracetemol",
                            Price = 9.75m,
                            TaxCategoryId = 5
                        },
                        new
                        {
                            Id = 9,
                            ImportTaxCategoryId = 2,
                            Name = "Imported Box of Chocolates",
                            Price = 11.25m,
                            TaxCategoryId = 4
                        });
                });

            modelBuilder.Entity("MAM_Sales_Tax.Models.TaxCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("TaxCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Uncategorised0",
                            Rate = 0m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Uncategorised10",
                            Rate = 10m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Books",
                            Rate = 0m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Food",
                            Rate = 0m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Medical",
                            Rate = 0m
                        });
                });

            modelBuilder.Entity("MAM_Sales_Tax.Models.Product", b =>
                {
                    b.HasOne("MAM_Sales_Tax.Models.ImportTaxCategory", "ImportTaxCategory")
                        .WithMany()
                        .HasForeignKey("ImportTaxCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MAM_Sales_Tax.Models.TaxCategory", "TaxCategory")
                        .WithMany()
                        .HasForeignKey("TaxCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportTaxCategory");

                    b.Navigation("TaxCategory");
                });
#pragma warning restore 612, 618
        }
    }
}
